on: [push, pull_request]
name: Linters
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1'

      - uses: actions/checkout@v4

      - name: Run go fmt
        run: |
          ./script/format

      - name: Run go vet
        run: |
          ./script/vet

      - name: Ensure go.mod is up-to-date
        run: |
          if [ $(go mod tidy && git diff | wc -l) -gt 0 ]; then git diff && exit 1; fi
